# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameTask', models.CharField(default='', max_length=128)),
                ('TaskText', models.TextField(blank=True, default='', max_length=128, null=True)),
                ('is_active', models.BooleanField(default=None)),
            ],
        ),
    ]
