# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171011_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='NameTask',
            field=models.CharField(max_length=128),
        ),
    ]
